git_lfs.lfs_server.*:
  type: config_entity
  label: 'Git LFS Server config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
