git_lfs.lfs_server.*:
  type: config_entity
  label: 'Git LFS Server config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    uuid:
      type: string
      label: 'UUID'
    description:
      type: text
      label: 'Description'
    status:
      type: boolean
      label: 'Status'
    repository_string:
      type: text
      label: 'GitHub Repository Owner/Name'
    repository_branch:
      type: text
      label: 'GitHub Repository Branch'
    repository_token:
      type: text
      label: 'GitHub Repository Access Token'
    lfs_protocol:
      type: text
      label: 'LFS Content Server Protocol'
    lfs_host:
      type: text
      label: 'LFS Content Server Hostname'
    lfs_port:
      type: text
      label: 'LFS Content Server Port'
    lfs_auth_user:
      type: text
      label: 'LFS Content Server User Name'
    lfs_auth_pass:
      type: text
      label: 'LFS Content Server User Password'
