git_lfs.lfs_server.*:
  type: config_entity
  label: 'Git LFS Server config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    uuid:
      type: string
      label: 'UUID'
    description:
      type: text
      label: 'Description'
    status:
      type: boolean
      label: 'Status'
    repository_string:
      type: text
      label: 'Repository Owner/Name'
    repository_branch:
      type: text
      label: 'Repository Branch'
    repository_token:
      type: text
      label: 'Repository Access Token'
